version: "3.9"

services:
    app:
        build: ./infra/php
        ports:
            - 5173:5173
        volumes:
            - ./infra/php/php.ini:/usr/local/etc/php/php.ini
            - ${HOST_VOLUME_DIR}:/var/www/html/
            # - vendor-store:/var/www/html/vendor #vendor volume mount
            # - node_modules-store:/var/www/html/node_modules #node_modules volume mount
            # - storage-framework-store:/var/www/html/storage/framework #storage volume mount

    web:
        image: nginx:1.22
        ports:
            - ${WEB_HOST_PORT}:80
        volumes:
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ${HOST_VOLUME_DIR}/public:/var/www/html/public #web public
        depends_on:
            - app

    db:
        build: ./infra/mysql
        ports:
            - ${DB_HOST_PORT}:3306
        volumes:
            - ./infra/mysql/my.cnf:/etc/my.cnf
            - db-store:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - TZ=${TIME_ZONE}

volumes:
    db-store:
    # vendor-store: #vendor
    # node_modules-store: #node_modules
    # storage-framework-store: #storage
